package format.text;

import format.text.CommonFormats;
import org.junit.Assert;
import org.junit.Test;

/**
 * Created by alext on 6/10/14.
 * TODO document class
 */
public class FormatTest {

    @Test
    public void test(){


        final String fastaRecord=">IDG9SXO01BPCPV\tBacteria(100);Firmicutes(100);Bacilli(100);Bacillales(100);Bacillaceae_1(100);Aeribacillus(100);\n" +
                "TACATGCAAGTCGAGCGGACCGAAGGGAGCTTGCTCCTTTAGGTTAGCGGCGGACGGGTGAGTAACACGTGGGCAACCTGCCCTGCAGACTGGGATAACTTCGGGAAACCGGAGCTAATACCGGATAACACCGAAAACCGCATGGTTTTCGGTTGAAAGGCGGCTTTTAGCTGTCACTGCAGGATGGGCCCGCGGCGCATTAGCTAGTTGGTGAGGTAACGGCTCACCAAGGCGACGATGCGTAGCCGACCTGAGAGGGTGACCGGCCACACTGGGACTGAGACACGGCCCAGACTCCTACGGGAGGCAGCAGTAGGGAATCTTCCGCAATGGACGAAAGTCTGACGGAGCAACGCCGCGTGAGCGAAGAAGGTCTTCGGATCGTAAAGCTCTGTTGTCAGGGAAGAACAAGTACCGTTCGAACAGGGCGGTACCTTGACGGTACCTGACGAGGAAGCCACGGCTAACTACGTG\n";


        final String ac= CommonFormats.FASTA.getAc(fastaRecord);
        System.out.println(ac);
        Assert.assertEquals(ac,"IDG9SXO01BPCPV\tBacteria(100);Firmicutes(100);Bacilli(100);Bacillales(100);Bacillaceae_1(100);Aeribacillus(100);");
        final String sequence=CommonFormats.FASTA.getSequence(fastaRecord);
        System.out.println(sequence);
        Assert.assertEquals(sequence,"TACATGCAAGTCGAGCGGACCGAAGGGAGCTTGCTCCTTTAGGTTAGCGGCGGACGGGTGAGTAACACGTGGGCAACCTGCCCTGCAGACTGGGATAACTTCGGGAAACCGGAGCTAATACCGGATAACACCGAAAACCGCATGGTTTTCGGTTGAAAGGCGGCTTTTAGCTGTCACTGCAGGATGGGCCCGCGGCGCATTAGCTAGTTGGTGAGGTAACGGCTCACCAAGGCGACGATGCGTAGCCGACCTGAGAGGGTGACCGGCCACACTGGGACTGAGACACGGCCCAGACTCCTACGGGAGGCAGCAGTAGGGAATCTTCCGCAATGGACGAAAGTCTGACGGAGCAACGCCGCGTGAGCGAAGAAGGTCTTCGGATCGTAAAGCTCTGTTGTCAGGGAAGAACAAGTACCGTTCGAACAGGGCGGTACCTTGACGGTACCTGACGAGGAAGCCACGGCTAACTACGTG");
    }
}
