//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.19 at 06:48:11 PM MSD 
//
/**
 * Java Bio is a free open source library for routine bioinformatics tasks.
 * Copyright (C) 2013  Alexander Tuzhikov
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package blast.output;

import javax.xml.bind.annotation.*;
import java.io.Serializable;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hitNum",
    "hitId",
    "hitDef",
    "hitAccession",
    "hitLen",
    "hitHsps"
})
@XmlRootElement(name = "Hit")
public class Hit implements Serializable {

    @XmlElement(name = "Hit_num", required = true)
    protected String hitNum;
    @XmlElement(name = "Hit_id", required = true)
    protected String hitId;
    @XmlElement(name = "Hit_def", required = true)
    protected String hitDef;
    @XmlElement(name = "Hit_accession", required = true)
    protected String hitAccession;
    @XmlElement(name = "Hit_len", required = true)
    protected String hitLen;
    @XmlElement(name = "Hit_hsps")
    protected HitHsps hitHsps;

    /**
     * Gets the value of the hitNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHitNum() {
        return hitNum;
    }

    /**
     * Sets the value of the hitNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHitNum(String value) {
        this.hitNum = value;
    }

    /**
     * Gets the value of the hitId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHitId() {
        return hitId;
    }

    /**
     * Sets the value of the hitId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHitId(String value) {
        this.hitId = value;
    }

    /**
     * Gets the value of the hitDef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHitDef() {
        return hitDef;
    }

    /**
     * Sets the value of the hitDef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHitDef(String value) {
        this.hitDef = value;
    }

    /**
     * Gets the value of the hitAccession property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHitAccession() {
        return hitAccession;
    }

    /**
     * Sets the value of the hitAccession property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHitAccession(String value) {
        this.hitAccession = value;
    }

    /**
     * Gets the value of the hitLen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHitLen() {
        return hitLen;
    }

    /**
     * Sets the value of the hitLen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHitLen(String value) {
        this.hitLen = value;
    }

    /**
     * Gets the value of the hitHsps property.
     * 
     * @return
     *     possible object is
     *     {@link HitHsps }
     *     
     */
    public HitHsps getHitHsps() {
        return hitHsps;
    }

    /**
     * Sets the value of the hitHsps property.
     * 
     * @param value
     *     allowed object is
     *     {@link HitHsps }
     *     
     */
    public void setHitHsps(HitHsps value) {
        this.hitHsps = value;
    }
 
}
