DROP TABLE APP.BLASTS;
DROP TABLE APP.ORFS;
DROP TABLE APP.CHROMOSOMES;
DROP TABLE APP.GENOMES;
DROP TABLE APP.PROGRESS;

CREATE TABLE APP.GENOMES
(
   ID_GENOME  INTEGER        GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   NAME       VARCHAR(255)   NOT NULL,
   COMMENT    VARCHAR(255)   NOT NULL
);

ALTER TABLE APP.GENOMES
   ADD CONSTRAINT PK_ID_GENOME
   PRIMARY KEY (ID_GENOME);

CREATE INDEX GENOME_NAME_IDX ON APP.GENOMES (NAME);

CREATE TABLE APP.CHROMOSOMES
(
   ID_CHROMOSOME  INTEGER        GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   ID_GENOME      INTEGER        NOT NULL,
   NAME           VARCHAR(255)   NOT NULL,
   SEQUENCE       CLOB           NOT NULL
);

ALTER TABLE APP.CHROMOSOMES
   ADD CONSTRAINT PK_ID_CHROMOSOME
   PRIMARY KEY (ID_CHROMOSOME);

ALTER TABLE APP.CHROMOSOMES
  ADD CONSTRAINT GENOME_ID_CHROM_REF FOREIGN KEY (ID_GENOME)
  REFERENCES APP.GENOMES (ID_GENOME)
  ON UPDATE RESTRICT
  ON DELETE CASCADE;

CREATE TABLE APP.ORFS
(
   ID_ORF         BIGINT        GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   ID_CHROMOSOME  INTEGER        NOT NULL,
   ID_GENOME      INTEGER        NOT NULL,
   FRAME          SMALLINT       NOT NULL,
   START          INTEGER        NOT NULL,
   STOP           INTEGER        NOT NULL,
   NAME           VARCHAR(255)   NOT NULL,
   SEQUENCE       CLOB           NOT NULL,
   LENGTH         INTEGER        NOT NULL
);

ALTER TABLE APP.ORFS
   ADD CONSTRAINT PK_ID_ORF
   PRIMARY KEY (ID_ORF);

ALTER TABLE APP.ORFS
  ADD CONSTRAINT GENOME_ID_ORF_REF FOREIGN KEY (ID_GENOME)
  REFERENCES APP.GENOMES (ID_GENOME)
  ON UPDATE RESTRICT
  ON DELETE CASCADE;

ALTER TABLE APP.ORFS
  ADD CONSTRAINT CHROMOSOME_ID_ORF_REF FOREIGN KEY (ID_CHROMOSOME)
  REFERENCES APP.CHROMOSOMES (ID_CHROMOSOME)
  ON UPDATE RESTRICT
  ON DELETE CASCADE;

CREATE INDEX ORF_LENGTH_IDX ON APP.ORFS (LENGTH);

CREATE TABLE APP.BLASTS
(
   ID_BLAST             BIGINT         GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   ID_QUERY_ORF         BIGINT         NOT NULL,
   ID_QUERY_GENOME      INTEGER        NOT NULL,
   ID_TARGET_ORF        BIGINT         NOT NULL,
   ID_TARGET_GENOME     INTEGER        NOT NULL,
   ITERATION            CLOB           NOT NULL,
   SCORE                DOUBLE         NOT NULL
);

ALTER TABLE APP.BLASTS
   ADD CONSTRAINT PK_ID_BLAST
   PRIMARY KEY (ID_BLAST);

ALTER TABLE APP.BLASTS
  ADD CONSTRAINT QUERY_ORF_ID_BLAST_REF FOREIGN KEY (ID_QUERY_ORF)
  REFERENCES APP.ORFS (ID_ORF)
  ON UPDATE RESTRICT
  ON DELETE CASCADE;

ALTER TABLE APP.BLASTS
  ADD CONSTRAINT TARGET_ORF_ID_BLAST_REF FOREIGN KEY (ID_TARGET_ORF)
  REFERENCES APP.ORFS (ID_ORF)
  ON UPDATE RESTRICT
  ON DELETE CASCADE;

ALTER TABLE APP.BLASTS
  ADD CONSTRAINT QUERY_GENOME_ID_BLAST_REF FOREIGN KEY (ID_QUERY_GENOME)
  REFERENCES APP.GENOMES (ID_GENOME)
  ON UPDATE RESTRICT
  ON DELETE CASCADE;

ALTER TABLE APP.BLASTS
  ADD CONSTRAINT TARGET_GENOME_ID_BLAST_REF FOREIGN KEY (ID_TARGET_GENOME)
  REFERENCES APP.GENOMES (ID_GENOME)
  ON UPDATE RESTRICT
  ON DELETE CASCADE;

CREATE INDEX BLAST_SCORE_IDX ON APP.BLASTS (SCORE);

CREATE TABLE APP.PROGRESS
(
   ID_PROGRESS             INTEGER        GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   ID_QUERY_GENOME         INTEGER        NOT NULL,
   ID_TARGET_GENOME        INTEGER        NOT NULL
);

ALTER TABLE APP.PROGRESS
   ADD CONSTRAINT PK_ID_PROGRESS
   PRIMARY KEY (ID_PROGRESS);

ALTER TABLE APP.PROGRESS
  ADD CONSTRAINT QUERY_GENOME_ID_PROGRESS_REF FOREIGN KEY (ID_QUERY_GENOME)
  REFERENCES APP.GENOMES (ID_GENOME)
  ON UPDATE RESTRICT
  ON DELETE CASCADE;

ALTER TABLE APP.PROGRESS
  ADD CONSTRAINT TARGET_GENOME_ID_PROGRESS_REF FOREIGN KEY (ID_TARGET_GENOME)
  REFERENCES APP.GENOMES (ID_GENOME)
  ON UPDATE RESTRICT
  ON DELETE CASCADE;

COMMIT;
