DROP TABLE APP.GENOMES;

CREATE TABLE APP.GENOMES
(
   ID_GENOME  INTEGER        GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   NAME       VARCHAR(255)   NOT NULL,
   COMMENT    VARCHAR(255)   NOT NULL
);

ALTER TABLE APP.GENOMES
   ADD CONSTRAINT PK_ID_GENOME
   PRIMARY KEY (ID_GENOME);

DROP TABLE APP.CHROMOSOMES;

CREATE TABLE APP.CHROMOSOMES
(
   ID_CHROMOSOME  INTEGER        GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   ID_GENOME      INTEGER        NOT NULL,
   NAME           VARCHAR(255)   NOT NULL,
   SEQUENCE       BLOB           NOT NULL
);

ALTER TABLE APP.CHROMOSOMES
   ADD CONSTRAINT PK_ID_CHROMOSOME
   PRIMARY KEY (ID_CHROMOSOME);

ALTER TABLE APP.CHROMOSOMES
  ADD CONSTRAINT GENOME_ID_CHROM_REF FOREIGN KEY (ID_GENOME)
  REFERENCES APP.GENOMES (ID_GENOME)
  ON UPDATE RESTRICT
  ON DELETE CASCADE;
  
DROP TABLE APP.ORFS;

CREATE TABLE APP.ORFS
(
   ID_ORF         BIGINT        GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   ID_CHROMOSOME  INTEGER        NOT NULL,
   ID_GENOME      INTEGER        NOT NULL,
   FRAME          SMALLINT       NOT NULL,
   START          INTEGER        NOT NULL,
   STOP           INTEGER        NOT NULL,
   NAME           VARCHAR(255)   NOT NULL,
   SEQUENCE       CLOB           NOT NULL,
   LENGTH         INTEGER        NOT NULL
);

ALTER TABLE APP.ORFS
   ADD CONSTRAINT PK_ID_ORF
   PRIMARY KEY (ID_ORF);

ALTER TABLE APP.ORFS
  ADD CONSTRAINT GENOME_ID_ORF_REF FOREIGN KEY (ID_GENOME)
  REFERENCES APP.GENOMES (ID_GENOME)
  ON UPDATE RESTRICT
  ON DELETE CASCADE;

ALTER TABLE APP.ORFS
  ADD CONSTRAINT CHROMOSOME_ID_ORF_REF FOREIGN KEY (ID_CHROMOSOME)
  REFERENCES APP.CHROMOSOMES (ID_CHROMOSOME)
  ON UPDATE RESTRICT
  ON DELETE CASCADE;

COMMIT;
