//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.06 at 12:20:21 PM EDT 
//


package properties.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dbConnection",
    "blastProperties",
    "genome"
})
@XmlRootElement(name = "gBlasterProperties")
public class GBlasterProperties {

    @XmlElement(name = "DBConnection", required = true)
    protected DBConnection dbConnection;
    @XmlElement(name = "BlastProperties", required = true)
    protected BlastProperties blastProperties;
    @XmlElement(name = "Genome")
    protected List<Genome> genome;

    /**
     * Gets the value of the dbConnection property.
     * 
     * @return
     *     possible object is
     *     {@link DBConnection }
     *     
     */
    public DBConnection getDBConnection() {
        return dbConnection;
    }

    /**
     * Sets the value of the dbConnection property.
     * 
     * @param value
     *     allowed object is
     *     {@link DBConnection }
     *     
     */
    public void setDBConnection(DBConnection value) {
        this.dbConnection = value;
    }

    /**
     * Gets the value of the blastProperties property.
     * 
     * @return
     *     possible object is
     *     {@link BlastProperties }
     *     
     */
    public BlastProperties getBlastProperties() {
        return blastProperties;
    }

    /**
     * Sets the value of the blastProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link BlastProperties }
     *     
     */
    public void setBlastProperties(BlastProperties value) {
        this.blastProperties = value;
    }

    /**
     * Gets the value of the genome property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the genome property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGenome().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Genome }
     * 
     * 
     */
    public List<Genome> getGenome() {
        if (genome == null) {
            genome = new ArrayList<Genome>();
        }
        return this.genome;
    }

}
