//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.16 at 06:37:53 PM EDT 
//


package properties.jaxb;

import javax.xml.bind.annotation.*;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "pathToFile",
    "geneticTable"
})
@XmlRootElement(name = "Genome")
public class Genome {

    @XmlElement(name = "Name", required = true)
    protected Name name;
    @XmlElement(name = "PathToFile", required = true)
    protected PathToFile pathToFile;
    @XmlElement(name = "GeneticTable", required = true)
    protected GeneticTable geneticTable;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Name }
     *     
     */
    public Name getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Name }
     *     
     */
    public void setName(Name value) {
        this.name = value;
    }

    /**
     * Gets the value of the pathToFile property.
     * 
     * @return
     *     possible object is
     *     {@link PathToFile }
     *     
     */
    public PathToFile getPathToFile() {
        return pathToFile;
    }

    /**
     * Sets the value of the pathToFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link PathToFile }
     *     
     */
    public void setPathToFile(PathToFile value) {
        this.pathToFile = value;
    }

    /**
     * Gets the value of the geneticTable property.
     * 
     * @return
     *     possible object is
     *     {@link GeneticTable }
     *     
     */
    public GeneticTable getGeneticTable() {
        return geneticTable;
    }

    /**
     * Sets the value of the geneticTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneticTable }
     *     
     */
    public void setGeneticTable(GeneticTable value) {
        this.geneticTable = value;
    }

}
