//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.06 at 12:20:21 PM EDT 
//


package properties.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DBConnection }
     * 
     */
    public DBConnection createDBConnection() {
        return new DBConnection();
    }

    /**
     * Create an instance of {@link GBlasterProperties }
     * 
     */
    public GBlasterProperties createGBlasterProperties() {
        return new GBlasterProperties();
    }

    /**
     * Create an instance of {@link BlastProperties }
     * 
     */
    public BlastProperties createBlastProperties() {
        return new BlastProperties();
    }

    /**
     * Create an instance of {@link Genome }
     * 
     */
    public Genome createGenome() {
        return new Genome();
    }

    /**
     * Create an instance of {@link MinORFLength }
     * 
     */
    public MinORFLength createMinORFLength() {
        return new MinORFLength();
    }

    /**
     * Create an instance of {@link MaxORFLength }
     * 
     */
    public MaxORFLength createMaxORFLength() {
        return new MaxORFLength();
    }

    /**
     * Create an instance of {@link PathToBlastP }
     * 
     */
    public PathToBlastP createPathToBlastP() {
        return new PathToBlastP();
    }

    /**
     * Create an instance of {@link PathToMakeBlastDb }
     * 
     */
    public PathToMakeBlastDb createPathToMakeBlastDb() {
        return new PathToMakeBlastDb();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link AlterCodon }
     * 
     */
    public AlterCodon createAlterCodon() {
        return new AlterCodon();
    }

    /**
     * Create an instance of {@link Expect }
     * 
     */
    public Expect createExpect() {
        return new Expect();
    }

    /**
     * Create an instance of {@link GeneticTable }
     * 
     */
    public GeneticTable createGeneticTable() {
        return new GeneticTable();
    }

    /**
     * Create an instance of {@link FastaType }
     * 
     */
    public FastaType createFastaType() {
        return new FastaType();
    }

    /**
     * Create an instance of {@link PathToFile }
     * 
     */
    public PathToFile createPathToFile() {
        return new PathToFile();
    }

}
